version: "3"

services:
  database:
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    env_file:
      - environment/.env.${NODE_ENV:-development}
    ports:
      - ${DATABASE_PORT:-27017}:27017
volumes:
  mongodata:
